disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Joseph Wardle"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Joseph Wardle"
  email = "joseph.m.wardle@gmail.com"
  image = "img/profile.jpg"
#   imageQuality = 96
  headline = "Student TD and Graphics Programmer â€” USD, GPU Programming, and Tools Development"
  bio = "Student TD and Graphics Programmer"
  links = [
    { email = "mailto:joseph.m.wardle@gmail.com" },
    { github = "https://github.com/joseph-wardle" },
    { linkedin = "https://www.linkedin.com/in/joseph-wardle-7b4b621b4/" }
  ]
